version: "3.0"
services:
  api:
    build:
      context: "./api"
    ports:
      - "${PORT}:8000"
    environment:
      MODEL_NAME: ${MODEL_NAME}
      MODEL_ENDPOINT: "http://ollama:11434"
      RABBIT_ENDPOINT: "amqp://rabbit:5672"
      JWT_AUDIENCE: ${JWT_AUDIENCE}
      JWKS_ENDPOINT: ${JWKS_ENDPOINT}
      AWS_REGION: ${AWS_REGION}
      AWS_KEY_ID: ${AWS_KEY_ID}
      AWS_ACCESS_KEY: ${AWS_ACCESS_KEY}
      SQS_ENDPOINT: ${SQS_ENDPOINT}
    depends_on:
      - ollama
    restart: always

  rabbit:
    image: rabbitmq
    ports:
      - "5672:5672"

  ollama:
    build:
      context: ./ollama
      dockerfile: Dockerfile
      args:
        MODEL_NAME: ${MODEL_NAME}
    ports:
      - "11434:11434"
